apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "goapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "goapp.name" . }}
    spec:
      containers:
        - name: {{ include "goapp.name" . }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ printf "%q" .value }}
{{- end }}
