name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches: [ main, sprint ]
    paths:
      - 'go-app/**'
      - '.github/workflows/docker-build-push.yaml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  GO_APP_IMAGE_NAME: ${{ github.repository }}/go-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Monolith
        id: meta-go-app
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.GO_APP_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push Go App Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./go-app
          push: true
          tags: ${{ steps.meta-go-app.outputs.tags }}
          labels: ${{ steps.meta-go-app.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
